name: CI
 
on: 
  [push, pull_request] 
 
env:
  BUILD_TYPE: Debug 
 
jobs: 
  build: 
    runs-on: ubuntu-latest 
 
    steps: 
    - name: Checkout repository
      uses: actions/checkout@v3 

    - name: Install nlohmann-json
      working-directory: ${{github.workspace}}        
      run: sudo apt install -y nlohmann-json3-dev
    
    - name: Install gmoke
      working-directory: ${{github.workspace}}     
      run: sudo apt-get install google-mock
 
    - name: Build
      working-directory: ${{github.workspace}} 
      run: make build-debug

    - name: Test
      working-directory: ${{github.workspace}} 
      run: make test-debug
 
    - name: Install lcov         
      run: |          
          sudo apt-get install -y lcov
          
    - name: Run coverage analyse
      run: |
          cd build_debug && lcov -t "SourceTil" -o coverage.info -c -d ./

    - name: Get coverage page
      run: |
          cd build_debug && genhtml -o report coverage.info
 
    - name: Load coverage result
      uses: actions/upload-artifact@v3
      with:
        name: Coverage
        path: build_debug/report/*
 
